name: ci

on:
  push:
    branches: [master, develop]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push [Production]
        id: docker_build_prod
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        with:
          push: true
          tags: |
            orionprotocol/orion-broker:latest
            orionprotocol/orion-broker:production
      -
        name: Build and push [Staging]
        id: docker_build_staging
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        with:
          push: true
          tags: orionprotocol/orion-broker:staging

      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
